import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    th: {
        // Navigation
        nav: {
            home: 'หน้าแรก',
            explore: 'สำรวจ',
            soul: 'โซล',
            chat: 'แชท',
            me: 'ฉัน',
        },
        // Auth
        auth: {
            welcomeBack: 'ยินดีต้อนรับ',
            joinFlare: 'เข้าร่วม Flare',
            signInContinue: 'เข้าสู่ระบบเพื่อดำเนินการต่อ',
            startSharing: 'เริ่มแชร์โมเมนต์ของคุณวันนี้',
            fullName: 'ชื่อ-นามสกุล',
            username: 'ชื่อผู้ใช้',
            email: 'อีเมล หรือ เบอร์โทรศัพท์',
            password: 'รหัสผ่าน',
            signIn: 'เข้าสู่ระบบ',
            createAccount: 'สร้างบัญชี',
            orContinueWith: 'หรือดำเนินการต่อด้วย',
            noAccount: 'ยังไม่มีบัญชี?',
            haveAccount: 'มีบัญชีอยู่แล้ว?',
            signUp: 'สมัครสมาชิก',
            sendCode: 'ส่งรหัส',
            verifyCode: 'ยืนยันรหัส',
            processing: 'กำลังดำเนินการ...',
            emailOtp: 'OTP อีเมล',
            usePassword: 'ใช้รหัสผ่าน',
            sixDigitCode: 'รหัส 6 หลัก',
            forgotPassword: 'ลืมรหัสผ่าน?',
            referralCode: 'รหัสแนะนำ (ถ้ามี)',
        },
        // Profile
        profile: {
            editProfile: 'แก้ไขโปรไฟล์',
            moments: 'โมเมนต์',
            fans: 'แฟนคลับ',
            following: 'กำลังติดตาม',
            liked: 'ถูกใจ',
            saved: 'บันทึก',
            shareFirstMoment: 'แชร์โมเมนต์แรกของคุณ!',
            yourName: 'ชื่อของคุณ',
            writeBio: 'เขียนแนะนำตัว...',
            save: 'บันทึก',
            cancel: 'ยกเลิก',
            saving: 'กำลังบันทึก...',
            joined: 'เข้าร่วมเมื่อ',
        },
        // Feed
        feed: {
            title: 'Flare',
            createMoment: 'สร้างโมเมนต์',
            whatsOnMind: 'คุณกำลังคิดอะไรอยู่?',
            post: 'โพสต์',
            posting: 'กำลังโพสต์...',
            loadingMoments: 'กำลังโหลดโมเมนต์...',
            noMoments: 'ยังไม่มีโมเมนต์ เป็นคนแรกที่แชร์สิ!',
            momentShared: 'แชร์โมเมนต์สำเร็จ! ✨',
            reported: 'รายงานโพสต์แล้ว ขอบคุณที่แจ้งให้เราทราบ',
            userBlocked: 'บล็อกผู้ใช้แล้ว คุณจะไม่เห็นโพสต์จากคนนี้อีก',
            removedSaved: 'เอาออกจากรายการบันทึกแล้ว',
            delete: 'ลบ',
            deleteMoment: 'ลบโมเมนต์?',
            deleteWarning: 'การกระทำนี้ไม่สามารถย้อนกลับได้',
            momentDeleted: 'ลบโมเมนต์สำเร็จ',
            comments: 'ความคิดเห็น',
            addComment: 'เพิ่มความคิดเห็น...',
            beFirstComment: 'เป็นคนแรกที่แสดงความคิดเห็น!',
            commentAdded: 'แสดงความคิดเห็นสำเร็จ!',
            errorLoadingComments: 'ไม่สามารถโหลดความคิดเห็นได้',
        },
        // Notifications
        notifications: {
            title: 'การแจ้งเตือน',
            clearAll: 'ล้างทั้งหมด',
            noNotifications: 'คุณไม่มีการแจ้งเตือนใหม่ในขณะนี้',
        },
        // Settings
        settings: {
            title: 'ตั้งค่า',
            // Categories
            account: 'บัญชี',
            general: 'ทั่วไป',
            privacySecurity: 'ความเป็นส่วนตัวและความปลอดภัย',
            notificationsSound: 'การแจ้งเตือนและเสียง',
            chatSettings: 'การตั้งค่าแชท',
            storageData: 'พื้นที่จัดเก็บและข้อมูล',
            support: 'ช่วยเหลือ',
            // Account
            personalInfo: 'ข้อมูลส่วนตัว',
            personalInfoDesc: 'ชื่อ, อีเมล, เบอร์โทร',
            changePassword: 'เปลี่ยนรหัสผ่าน',
            changePasswordDesc: 'อัปเดตรหัสผ่านของคุณ',
            linkedAccounts: 'บัญชีที่เชื่อมต่อ',
            linkedAccountsDesc: 'Google, Facebook, LINE',
            verifyAccount: 'ยืนยันบัญชี',
            verifyAccountDesc: 'รับเครื่องหมายยืนยันตัวตน',
            // General
            language: 'ภาษา',
            languageDesc: 'เปลี่ยนภาษาแอปพลิเคชัน',
            appearance: 'ธีมหน้าตา',
            appearanceDesc: 'โหมดมืด, โหมดสว่าง, ระบบ',
            fontSize: 'ขนาดตัวอักษร',
            fontSizeDesc: 'ปรับขนาดข้อความในแอป',
            themeColor: 'สีธีม',
            themeColorDesc: 'เปลี่ยนสีหลักของแอป',
            // Privacy & Security
            profileVisibility: 'การมองเห็นโปรไฟล์',
            profileVisibilityDesc: 'สาธารณะ, เฉพาะเพื่อน, ส่วนตัว',
            onlineStatus: 'สถานะออนไลน์',
            onlineStatusDesc: 'แสดงสถานะออนไลน์ของคุณ',
            readReceipts: 'แจ้งอ่านแล้ว',
            readReceiptsDesc: 'แสดงเมื่อคุณอ่านข้อความ',
            twoFactor: 'ยืนยันตัวตนสองชั้น',
            twoFactorDesc: 'เพิ่มความปลอดภัยให้บัญชี',
            blockedUsers: 'ผู้ใช้ที่ถูกบล็อก',
            blockedUsersDesc: 'จัดการรายชื่อที่ถูกบล็อก',
            loginActivity: 'กิจกรรมการเข้าสู่ระบบ',
            loginActivityDesc: 'ดูอุปกรณ์ที่เข้าสู่ระบบ',
            // Notifications
            pushNotifications: 'การแจ้งเตือนแบบพุช',
            pushNotificationsDesc: 'แจ้งเตือนบนหน้าจอ',
            notifSound: 'เสียงแจ้งเตือน',
            notifSoundDesc: 'เปิด/ปิดเสียงแจ้งเตือน',
            vibration: 'การสั่น',
            vibrationDesc: 'สั่นเมื่อได้รับแจ้งเตือน',
            notifLikes: 'การกดถูกใจ',
            notifLikesDesc: 'แจ้งเตือนเมื่อมีคนกดถูกใจ',
            notifComments: 'ความคิดเห็น',
            notifCommentsDesc: 'แจ้งเตือนเมื่อมีคนคอมเมนต์',
            notifMessages: 'ข้อความ',
            notifMessagesDesc: 'แจ้งเตือนเมื่อได้รับข้อความ',
            notifMatches: 'การแมตช์',
            notifMatchesDesc: 'แจ้งเตือนเมื่อมีการแมตช์ใหม่',
            // Chat
            chatBubbleStyle: 'สไตล์ฟองแชท',
            chatBubbleStyleDesc: 'เปลี่ยนรูปแบบฟองข้อความ',
            autoDeleteMessages: 'ลบข้อความอัตโนมัติ',
            autoDeleteMessagesDesc: 'ตั้งเวลาลบข้อความ',
            chatWallpaper: 'ภาพพื้นหลังแชท',
            chatWallpaperDesc: 'ปรับแต่งพื้นหลังแชท',
            mediaAutoDownload: 'ดาวน์โหลดมีเดียอัตโนมัติ',
            mediaAutoDownloadDesc: 'รูป, วิดีโอ, ไฟล์',
            // Storage
            clearCache: 'ล้างแคช',
            clearCacheDesc: 'ลบข้อมูลที่แคชไว้',
            dataUsage: 'การใช้ข้อมูล',
            dataUsageDesc: 'ดูปริมาณข้อมูลที่ใช้',
            downloadData: 'ดาวน์โหลดข้อมูลของฉัน',
            downloadDataDesc: 'ส่งออกข้อมูลทั้งหมดของคุณ',
            // Support
            helpCenter: 'ศูนย์ช่วยเหลือ',
            helpCenterDesc: 'คำถามที่พบบ่อยและแนวทาง',
            reportProblem: 'รายงานปัญหา',
            reportProblemDesc: 'แจ้งข้อผิดพลาดหรือปัญหา',
            termsOfService: 'เงื่อนไขการใช้งาน',
            termsOfServiceDesc: 'อ่านข้อกำหนดของเรา',
            privacyPolicy: 'นโยบายความเป็นส่วนตัว',
            privacyPolicyDesc: 'วิธีที่เราจัดการข้อมูลของคุณ',
            about: 'เกี่ยวกับ',
            aboutDesc: 'เวอร์ชันแอปและข้อมูล',
            // Actions
            logout: 'ออกจากระบบ',
            logoutDesc: 'ออกจากระบบบัญชีนี้',
            deleteAccount: 'ลบบัญชี',
            deleteAccountDesc: 'ลบบัญชีและข้อมูลทั้งหมดอย่างถาวร',
            // Values
            public: 'สาธารณะ',
            friendsOnly: 'เฉพาะเพื่อน',
            private: 'ส่วนตัว',
            dark: 'มืด',
            light: 'สว่าง',
            system: 'ตามระบบ',
            small: 'เล็ก',
            medium: 'กลาง',
            large: 'ใหญ่',
            never: 'ไม่เคย',
            after24h: 'หลัง 24 ชม.',
            after7d: 'หลัง 7 วัน',
            after30d: 'หลัง 30 วัน',
            round: 'มน',
            sharp: 'เหลี่ยม',
            minimal: 'มินิมอล',
            version: 'เวอร์ชัน',
            cacheCleared: 'ล้างแคชเรียบร้อยแล้ว',
            noBlockedUsers: 'ไม่มีผู้ใช้ที่ถูกบล็อก',
            unblock: 'เลิกบล็อก',
        },
        // Soul Game
        soul: {
            swipe: 'ปัด',
            discoverNewFriends: 'ค้นหาเพื่อนใหม่ที่ตรงใจคุณ',
            setupTitle: 'ตั้งค่า Soul Profile',
            setupSubtitle: 'โปรไฟล์ Soul จะแยกจากโปรไฟล์หลักของคุณ เพื่อความเป็นส่วนตัวในการหาเพื่อนใหม่',
            importProfile: 'ดึงจากโปรไฟล์หลัก',
            importDesc: 'คัดลอกชื่อ, รูป, bio จากโปรไฟล์หลักมาเริ่มต้น แก้ไขได้ทีหลัง',
            createNew: 'สร้างโปรไฟล์ใหม่',
            createNewDesc: 'กรอกข้อมูลใหม่ทั้งหมด สร้างตัวตนอีกแบบได้เลย!',
            profileReady: '✨ Soul Profile ของคุณพร้อมแล้ว! เริ่มหาเพื่อนใหม่กันเลย!',
            resetProfile: 'ตั้งค่า Soul Profile ใหม่',
            discover: 'ค้นพบ',
            connecting: 'กำลังเชื่อมต่อกับวิญญาณ...',
            noMoreSouls: 'ไม่มีเพื่อนใหม่ในบริเวณนี้',
            seenEveryone: 'คุณดูโปรไฟล์ทั้งหมดในตอนนี้แล้ว',
            findMore: 'หาเพื่อนใหม่เพิ่ม',
            matchWith: 'แมตช์กับ {{name}} แล้ว! ❤️',
            rewinded: 'ย้อนกลับแล้ว ⏪',
            noRewind: 'ไม่มีโปรไฟล์ก่อนหน้าให้ย้อนกลับ',
            superLiked: 'คุณ Super Like {{name}}! ⚡',
            openingProfile: 'กำลังเปิดโปรไฟล์...',
            identityRevealed: 'เปิดเผยตัวตนแล้ว! ✨ ตอนนี้เห็นโปรไฟล์จริงได้แล้ว!',
            identityRequested: 'ส่งคำขอเปิดเผยแล้ว ❤️ รออีกฝ่ายกดยอมรับ',
            identityError: 'เปิดเผยตัวตนไม่สำเร็จ',
            updated: '✨ อัปเดต Soul Profile เรียบร้อยแล้ว!',
            mainProfileHint: 'โปรไฟล์หลัก: {{name}}',
            basicInfo: '📝 ข้อมูลพื้นฐาน',
            tapToChange: 'แตะเพื่อเปลี่ยนรูป Soul',
            displayName: 'ชื่อที่แสดง',
            displayNamePlaceholder: 'ชื่อที่ต้องการแสดงใน Soul',
            bioPlaceholder: 'เขียนแนะนำตัวสั้นๆ...',
            age: 'อายุ',
            gender: 'เพศ',
            male: 'ชาย',
            female: 'หญิง',
            other: 'อื่นๆ',
            location: 'ที่อยู่ (จังหวัด)',
            selectProvince: '-- เลือกจังหวัด --',
            interestsTitle: '🎯 สิ่งที่สนใจ',
            interestsHint: 'เลือกสิ่งที่คุณชอบ (1-6 อย่าง) · เลือกแล้ว {{count}}/6',
            lookingForTitle: '💭 กำลังมองหาอะไร?',
            lookingForHint: 'เลือกได้มากกว่า 1 อย่าง',
            photosTitle: '📸 รูปภาพของคุณ',
            photosHint: 'กรุณาอัปโหลดรูปภาพอย่างน้อย 2 รูปเพื่อให้โปรไฟล์ดูน่าสนใจ',
            previewTitle: '✨ ตัวอย่างโปรไฟล์ Soul',
            lookingForLabel: 'กำลังมองหา:',
            startSoul: 'เริ่มต้นใช้งาน Soul!',
            viewLikedSouls: 'ดูคนที่คุณถูกใจ',
            editProfile: 'แก้ไข Soul Profile',
            destinyPulse: '⚡ Destiny Pulse!',
            destinyNearby: 'มีบางคนกำลังปัดหาคู่ในระยะใกล้กับคุณตอนนี้!',
            destinyIntense: 'พลังงานความเข้ากันได้สูงมาก! 🔥',
            viewPreview: 'ดูตัวอย่างโปรไฟล์',
            interests: {
                music: 'ดนตรี',
                movies: 'ภาพยนตร์',
                travel: 'ท่องเที่ยว',
                food: 'อาหาร',
                sports: 'กีฬา',
                gaming: 'เกม',
                art: 'ศิลปะ',
                reading: 'อ่านหนังสือ',
                photography: 'ถ่ายรูป',
                cooking: 'ทำอาหาร',
                fitness: 'ออกกำลังกาย',
                anime: 'อนิเมะ',
                nature: 'ธรรมชาติ',
                tech: 'เทคโนโลยี',
                fashion: 'แฟชั่น',
                coffee: 'กาแฟ',
                pet: 'สัตว์เลี้ยง',
                kpop: 'K-Pop',
            },
            looking: {
                friends: 'เพื่อนคุย',
                dating: 'หาคู่เดท',
                relationship: 'ความสัมพันธ์จริงจัง',
                hangout: 'ออกไปเที่ยวด้วยกัน',
                anything: 'อะไรก็ได้',
            },
        },
        // Chat
        chat: {
            search: 'ค้นหาแชท...',
            noChats: 'ยังไม่มีแชท',
            typeMessage: 'พิมพ์ข้อความ...',
            online: 'ออนไลน์',
            lastSeen: 'เห็นล่าสุด',
            blockedUser: 'บล็อก {{name}} เรียบร้อยแล้ว',
            reportedUser: 'รายงาน {{name}} เรียบร้อยแล้ว',
        },
        // Referral
        referral: {
            title: 'ชวนเพื่อนรับ VIP',
            desc: 'ชวนเพื่อนมาใช้ Flare รับสิทธิ์ VIP ฟรี 3 เดือน!',
            yourCode: 'รหัสแนะนำของคุณ',
            copy: 'คัดลอก',
            copied: 'คัดลอกแล้ว!',
            enterCode: 'กรอกรหัสแนะนำ',
            apply: 'ใช้รหัส',
            success: 'ยินดีด้วย! คุณได้รับสิทธิ์ VIP แล้ว',
            inviteCount: 'เพื่อนที่ชวนแล้ว: {{count}} คน',
            vipStatus: 'สถานะ VIP: {{status}}',
            vipUntil: 'ใช้งานได้ถึง: {{date}}',
            active: 'ใช้งานอยู่',
            inactive: 'ยังไม่ได้เปิดใช้งาน',
        },
        // Common
        common: {
            loading: 'กำลังโหลด...',
            error: 'ข้อผิดพลาด',
            success: 'สำเร็จ',
            confirm: 'ยืนยัน',
            cancel: 'ยกเลิก',
            close: 'ปิด',
            back: 'กลับ',
            next: 'ถัดไป',
            done: 'เสร็จ',
            on: 'เปิด',
            off: 'ปิด',
        },
    },
    en: {
        nav: {
            home: 'Home',
            explore: 'Explore',
            soul: 'Soul',
            chat: 'Chat',
            me: 'Me',
        },
        auth: {
            welcomeBack: 'Welcome',
            joinFlare: 'Join Flare',
            signInContinue: 'Sign in to continue your journey',
            startSharing: 'Start sharing your moments today',
            fullName: 'Full Name',
            username: 'Username',
            email: 'Email or Phone Number',
            password: 'Password',
            signIn: 'Sign In',
            createAccount: 'Create Account',
            orContinueWith: 'or continue with',
            noAccount: "Don't have an account?",
            haveAccount: 'Already have an account?',
            signUp: 'Sign Up',
            sendCode: 'Send Code',
            verifyCode: 'Verify Code',
            processing: 'Processing...',
            emailOtp: 'Email OTP',
            usePassword: 'Use Password',
            sixDigitCode: '6-digit Code',
            forgotPassword: 'Forgot Password?',
            referralCode: 'Referral Code (Optional)',
        },
        profile: {
            editProfile: 'Edit Profile',
            moments: 'Moments',
            fans: 'Fans',
            following: 'Following',
            liked: 'Liked',
            saved: 'Saved',
            shareFirstMoment: 'Share your first moment!',
            yourName: 'Your Name',
            writeBio: 'Write a bio...',
            save: 'Save',
            cancel: 'Cancel',
            saving: 'Saving...',
            joined: 'Joined',
        },
        feed: {
            title: 'Flare',
            createMoment: 'Create Moment',
            whatsOnMind: "What's on your mind?",
            post: 'Post',
            posting: 'Posting...',
            loadingMoments: 'Loading moments...',
            noMoments: 'No moments yet. Be the first to share!',
            momentShared: 'Moment shared successfully! ✨',
            reported: 'Post reported. Thank you for letting us know.',
            userBlocked: 'User blocked. You will no longer see posts from this user.',
            removedSaved: 'Removed from saved',
            delete: 'Delete',
            deleteMoment: 'Delete Moment?',
            deleteWarning: 'This action cannot be undone.',
            momentDeleted: 'Moment deleted successfully.',
            comments: 'Comments',
            addComment: 'Add a comment...',
            beFirstComment: 'Be the first to comment!',
            commentAdded: 'Comment added!',
            errorLoadingComments: 'Failed to load comments',
        },
        notifications: {
            title: 'Notifications',
            clearAll: 'Clear All',
            noNotifications: 'You have no new notifications',
        },
        settings: {
            title: 'Settings',
            account: 'Account',
            general: 'General',
            privacySecurity: 'Privacy & Security',
            notificationsSound: 'Notifications & Sound',
            chatSettings: 'Chat Settings',
            storageData: 'Storage & Data',
            support: 'Help & Support',
            personalInfo: 'Personal Information',
            personalInfoDesc: 'Name, email, phone',
            changePassword: 'Change Password',
            changePasswordDesc: 'Update your password',
            linkedAccounts: 'Linked Accounts',
            linkedAccountsDesc: 'Google, Facebook, LINE',
            verifyAccount: 'Verify Account',
            verifyAccountDesc: 'Get a verified badge',
            language: 'Language',
            languageDesc: 'Change app language',
            appearance: 'Appearance',
            appearanceDesc: 'Dark mode, Light mode, System',
            fontSize: 'Font Size',
            fontSizeDesc: 'Adjust text size in app',
            themeColor: 'Theme Color',
            themeColorDesc: 'Change primary color',
            profileVisibility: 'Profile Visibility',
            profileVisibilityDesc: 'Public, Friends only, Private',
            onlineStatus: 'Online Status',
            onlineStatusDesc: 'Show your online status',
            readReceipts: 'Read Receipts',
            readReceiptsDesc: 'Show when you read messages',
            twoFactor: 'Two-Factor Auth',
            twoFactorDesc: 'Add extra security to your account',
            blockedUsers: 'Blocked Users',
            blockedUsersDesc: 'Manage blocked list',
            loginActivity: 'Login Activity',
            loginActivityDesc: 'View logged-in devices',
            pushNotifications: 'Push Notifications',
            pushNotificationsDesc: 'On-screen notifications',
            notifSound: 'Notification Sound',
            notifSoundDesc: 'Enable/disable sound',
            vibration: 'Vibration',
            vibrationDesc: 'Vibrate on notification',
            notifLikes: 'Likes',
            notifLikesDesc: 'Notify when someone likes',
            notifComments: 'Comments',
            notifCommentsDesc: 'Notify on new comments',
            notifMessages: 'Messages',
            notifMessagesDesc: 'Notify on new messages',
            notifMatches: 'Matches',
            notifMatchesDesc: 'Notify on new matches',
            chatBubbleStyle: 'Chat Bubble Style',
            chatBubbleStyleDesc: 'Change message bubble style',
            autoDeleteMessages: 'Auto-Delete Messages',
            autoDeleteMessagesDesc: 'Set message expiry time',
            chatWallpaper: 'Chat Wallpaper',
            chatWallpaperDesc: 'Customize chat background',
            mediaAutoDownload: 'Media Auto-Download',
            mediaAutoDownloadDesc: 'Photos, videos, files',
            clearCache: 'Clear Cache',
            clearCacheDesc: 'Delete cached data',
            dataUsage: 'Data Usage',
            dataUsageDesc: 'View data consumption',
            downloadData: 'Download My Data',
            downloadDataDesc: 'Export all your data',
            helpCenter: 'Help Center',
            helpCenterDesc: 'FAQs and guides',
            reportProblem: 'Report a Problem',
            reportProblemDesc: 'Report bugs or issues',
            termsOfService: 'Terms of Service',
            termsOfServiceDesc: 'Read our terms',
            privacyPolicy: 'Privacy Policy',
            privacyPolicyDesc: 'How we handle your data',
            about: 'About',
            aboutDesc: 'App version and info',
            logout: 'Log Out',
            logoutDesc: 'Sign out of this account',
            deleteAccount: 'Delete Account',
            deleteAccountDesc: 'Permanently delete account and all data',
            public: 'Public',
            friendsOnly: 'Friends Only',
            private: 'Private',
            dark: 'Dark',
            light: 'Light',
            system: 'System',
            small: 'Small',
            medium: 'Medium',
            large: 'Large',
            never: 'Never',
            after24h: 'After 24h',
            after7d: 'After 7 days',
            after30d: 'After 30 days',
            round: 'Round',
            sharp: 'Sharp',
            minimal: 'Minimal',
            version: 'Version',
            cacheCleared: 'Cache cleared successfully',
            noBlockedUsers: 'No blocked users',
            unblock: 'Unblock',
        },
        soul: {
            swipe: 'Swipe',
            discoverNewFriends: 'Discover New Friends',
            setupTitle: 'Setup Soul Profile',
            setupSubtitle: 'Your Soul profile is separate from your main profile for privacy when meeting new people',
            importProfile: 'Import from Main Profile',
            importDesc: 'Copy name, photo, bio from your main profile. You can edit later.',
            createNew: 'Create New Profile',
            createNewDesc: 'Fill in all new details. Create a different persona!',
            profileReady: '✨ Your Soul Profile is ready! Start meeting new people!',
            resetProfile: 'Reset Soul Profile',
            discover: 'Discover',
            connecting: 'Connecting with Souls...',
            noMoreSouls: 'No more souls nearby',
            seenEveryone: "You've seen everyone around you for now.",
            findMore: 'Find More Souls',
            matchWith: "It's a Match with {{name}}! ❤️",
            rewinded: 'Rewinded ⏪',
            noRewind: 'No previous profiles to rewind.',
            superLiked: 'You Super Liked {{name}}! ⚡',
            openingProfile: 'Opening profile...',
            identityRevealed: 'Identity revealed! ✨ You can now see the real profile.',
            identityRequested: 'Reveal request sent ❤️ Waiting for approval.',
            identityError: 'Failed to reveal identity',
            updated: '✨ Soul Profile updated successfully!',
            mainProfileHint: 'Main Profile: {{name}}',
            basicInfo: '📝 Basic Info',
            tapToChange: 'Tap to change Soul photo',
            displayName: 'Display Name',
            displayNamePlaceholder: 'Your Soul display name',
            bioPlaceholder: 'Write a short intro...',
            age: 'Age',
            gender: 'Gender',
            male: 'Male',
            female: 'Female',
            other: 'Other',
            location: 'Location (Province)',
            selectProvince: '-- Select Province --',
            interestsTitle: '🎯 Your Interests',
            interestsHint: 'Pick what you enjoy (1-6 items) · Selected {{count}}/6',
            lookingForTitle: '💭 What are you looking for?',
            lookingForHint: 'You can select more than one',
            photosTitle: '📸 Your Photos',
            photosHint: 'Please upload at least 2 photos to make your profile more attractive.',
            previewTitle: '✨ Soul Profile Preview',
            lookingForLabel: 'Looking for:',
            startSoul: 'Start Using Soul!',
            viewLikedSouls: 'View Liked Souls',
            editProfile: 'Edit Soul Profile',
            destinyPulse: '⚡ Destiny Pulse!',
            destinyNearby: 'Someone nearby is swiping right now!',
            destinyIntense: 'High connection energy detected! 🔥',
            viewPreview: 'View Profile Preview',
            interests: {
                music: 'Music',
                movies: 'Movies',
                travel: 'Travel',
                food: 'Food',
                sports: 'Sports',
                gaming: 'Gaming',
                art: 'Art',
                reading: 'Reading',
                photography: 'Photography',
                cooking: 'Cooking',
                fitness: 'Fitness',
                anime: 'Anime',
                nature: 'Nature',
                tech: 'Technology',
                fashion: 'Fashion',
                coffee: 'Coffee',
                pet: 'Pets',
                kpop: 'K-Pop',
            },
            looking: {
                friends: 'Friends',
                dating: 'Dating',
                relationship: 'Relationship',
                hangout: 'Hangout',
                anything: 'Anything',
            },
        },
        chat: {
            search: 'Search chats...',
            noChats: 'No chats yet',
            typeMessage: 'Type a message...',
            online: 'Online',
            lastSeen: 'Last seen',
            blockedUser: 'Blocked {{name}} successfully',
            reportedUser: 'Reported {{name}} successfully',
        },
        // Referral
        referral: {
            title: 'Refer & Earn VIP',
            desc: 'Invite friends to Flare and get 3 months VIP for free!',
            yourCode: 'Your Referral Code',
            copy: 'Copy',
            copied: 'Copied!',
            enterCode: 'Enter Referral Code',
            apply: 'Apply',
            success: 'Congrats! You are now VIP',
            inviteCount: 'Friends Invited: {{count}}',
            vipStatus: 'VIP Status: {{status}}',
            vipUntil: 'Expires: {{date}}',
            active: 'Active',
            inactive: 'Inactive',
        },
        common: {
            loading: 'Loading...',
            error: 'Error',
            success: 'Success',
            confirm: 'Confirm',
            cancel: 'Cancel',
            close: 'Close',
            back: 'Back',
            next: 'Next',
            done: 'Done',
            on: 'On',
            off: 'Off',
        },
    },
    la: {
        nav: {
            home: 'ໜ້າຫຼັກ',
            explore: 'ສຳຫຼວດ',
            soul: 'ໂຊລ',
            chat: 'ແຊັດ',
            me: 'ຂ້ອຍ',
        },
        auth: {
            welcomeBack: 'ຍິນດີຕ້ອນຮັບ',
            joinFlare: 'ເຂົ້າຮ່ວມ Flare',
            signInContinue: 'ເຂົ້າສູ່ລະບົບເພື່ອດຳເນີນການຕໍ່',
            startSharing: 'ເລີ່ມແບ່ງປັນໂມເມນຂອງທ່ານມື້ນີ້',
            fullName: 'ຊື່ ແລະ ນາມສະກຸນ',
            username: 'ຊື່ຜູ້ໃຊ້',
            email: 'ອີເມວ ຫຼື ເບີໂທລະສັບ',
            password: 'ລະຫັດຜ່ານ',
            signIn: 'ເຂົ້າສູ່ລະບົບ',
            createAccount: 'ສ້າງບັນຊີ',
            orContinueWith: 'ຫຼື ດຳເນີນການຕໍ່ດ້ວຍ',
            noAccount: 'ຍັງບໍ່ມີບັນຊີ?',
            haveAccount: 'ມີບັນຊີຢູ່ແລ້ວ?',
            signUp: 'ສະໝັກສະມາຊິກ',
            sendCode: 'ສົ່ງລະຫັດ',
            verifyCode: 'ຢືນຢັນລະຫັດ',
            processing: 'ກຳລັງດຳເນີນການ...',
            emailOtp: 'OTP ອີເມວ',
            usePassword: 'ໃຊ້ລະຫັດຜ່ານ',
            sixDigitCode: 'ລະຫັດ 6 ຫຼັກ',
            forgotPassword: 'ລືມລະຫັດຜ່ານ?',
        },
        profile: {
            editProfile: 'ແກ້ໄຂໂປຣໄຟລ໌',
            moments: 'ໂມເມນ',
            fans: 'ແຟນຄັບ',
            following: 'ກຳລັງຕິດຕາມ',
            liked: 'ຖືກໃຈ',
            saved: 'ບັນທຶກ',
            shareFirstMoment: 'ແບ່ງປັນໂມເມນທຳອິດຂອງທ່ານ!',
            yourName: 'ຊື່ຂອງທ່ານ',
            writeBio: 'ຂຽນແນະນຳຕົວ...',
            save: 'ບັນທຶກ',
            cancel: 'ຍົກເລີກ',
            saving: 'ກຳລັງບັນທຶກ...',
            joined: 'ເຂົ້າຮ່ວມເມື່ອ',
        },
        feed: {
            title: 'Flare',
            createMoment: 'ສ້າງໂມເມນ',
            whatsOnMind: 'ທ່ານກຳລັງຄິດຫຍັງຢູ່?',
            post: 'ໂພສ',
            posting: 'ກຳລັງໂພສ...',
            loadingMoments: 'ກຳລັງໂຫຼດໂມເມນ...',
            noMoments: 'ຍັງບໍ່ມີໂມເມນ ເປັນຄົນທຳອິດທີ່ແບ່ງປັນ!',
            momentShared: 'ແບ່ງປັນໂມເມນສຳເລັດ! ✨',
            reported: 'ລາຍງານໂພສແລ້ວ ຂອບໃຈທີ່ແຈ້ງໃຫ້ພວກເຮົາຊາບ',
            userBlocked: 'ບລັອກຜູ້ໃຊ້ແລ້ວ ທ່ານຈະບໍ່ເຫັນໂພສຈາກຄົນນີ້ອີກ',
            removedSaved: 'ເອົາອອກຈາກລາຍການບັນທຶກແລ້ວ',
            delete: 'ລົບ',
            deleteMoment: 'ລົບໂມເມນ?',
            deleteWarning: 'ການກະທຳນີ້ບໍ່ສາມາດກັບຄືນໄດ້',
            momentDeleted: 'ລົບໂມເມນສຳເລັດ',
            comments: 'ຄວາມຄິດເຫັນ',
            addComment: 'ເພີ່ມຄວາມຄິດເຫັນ...',
            beFirstComment: 'ເປັນຄົນທຳອິດທີ່ສະແດງຄວາມຄິດເຫັນ!',
            commentAdded: 'ສະແດງຄວາມຄິດເຫັນສຳເລັດ!',
            errorLoadingComments: 'ບໍ່ສາມາດໂຫຼດຄວາມຄິດເຫັນໄດ້',
        },
        notifications: {
            title: 'ການແຈ້ງເຕືອນ',
            clearAll: 'ລ້າງທັງໝົດ',
            noNotifications: 'ທ່ານບໍ່ມີການແຈ້ງເຕືອນໃໝ່ໃນເວລານີ້',
        },
        settings: {
            title: 'ຕັ້ງຄ່າ',
            account: 'ບັນຊີ',
            general: 'ທົ່ວໄປ',
            privacySecurity: 'ຄວາມເປັນສ່ວນຕົວ ແລະ ຄວາມປອດໄພ',
            notificationsSound: 'ການແຈ້ງເຕືອນ ແລະ ສຽງ',
            chatSettings: 'ການຕັ້ງຄ່າແຊັດ',
            storageData: 'ພື້ນທີ່ຈັດເກັບ ແລະ ຂໍ້ມູນ',
            support: 'ຊ່ວຍເຫຼືອ',
            personalInfo: 'ຂໍ້ມູນສ່ວນຕົວ',
            personalInfoDesc: 'ຊື່, ອີເມວ, ເບີໂທ',
            changePassword: 'ປ່ຽນລະຫັດຜ່ານ',
            changePasswordDesc: 'ອັບເດດລະຫັດຜ່ານຂອງທ່ານ',
            linkedAccounts: 'ບັນຊີທີ່ເຊື່ອມຕໍ່',
            linkedAccountsDesc: 'Google, Facebook, LINE',
            verifyAccount: 'ຢືນຢັນບັນຊີ',
            verifyAccountDesc: 'ຮັບເຄື່ອງໝາຍຢືນຢັນຕົວຕົນ',
            language: 'ພາສາ',
            languageDesc: 'ປ່ຽນພາສາແອັບພລິເຄຊັນ',
            appearance: 'ທີມໜ້າຕາ',
            appearanceDesc: 'ໂໝດມືດ, ໂໝດສະຫວ່າງ, ລະບົບ',
            fontSize: 'ຂະໜາດຕົວອັກສອນ',
            fontSizeDesc: 'ປັບຂະໜາດຂໍ້ຄວາມໃນແອັບ',
            themeColor: 'ສີທີມ',
            themeColorDesc: 'ປ່ຽນສີຫຼັກຂອງແອັບ',
            profileVisibility: 'ການເບິ່ງເຫັນໂປຣໄຟລ໌',
            profileVisibilityDesc: 'ສາທາລະນະ, ສະເພາະໝູ່, ສ່ວນຕົວ',
            onlineStatus: 'ສະຖານະອອນໄລນ໌',
            onlineStatusDesc: 'ສະແດງສະຖານະອອນໄລນ໌ຂອງທ່ານ',
            readReceipts: 'ແຈ້ງອ່ານແລ້ວ',
            readReceiptsDesc: 'ສະແດງເມື່ອທ່ານອ່ານຂໍ້ຄວາມ',
            twoFactor: 'ຢືນຢັນຕົວຕົນສອງຊັ້ນ',
            twoFactorDesc: 'ເພີ່ມຄວາມປອດໄພໃຫ້ບັນຊີ',
            blockedUsers: 'ຜູ້ໃຊ້ທີ່ຖືກບລັອກ',
            blockedUsersDesc: 'ຈັດການລາຍຊື່ທີ່ຖືກບລັອກ',
            loginActivity: 'ກິດຈະກຳການເຂົ້າສູ່ລະບົບ',
            loginActivityDesc: 'ເບິ່ງອຸປະກອນທີ່ເຂົ້າສູ່ລະບົບ',
            pushNotifications: 'ການແຈ້ງເຕືອນແບບພຸຊ',
            pushNotificationsDesc: 'ແຈ້ງເຕືອນເທິງໜ້າຈໍ',
            notifSound: 'ສຽງແຈ້ງເຕືອນ',
            notifSoundDesc: 'ເປີດ/ປິດສຽງແຈ້ງເຕືອນ',
            vibration: 'ການສັ່ນ',
            vibrationDesc: 'ສັ່ນເມື່ອໄດ້ຮັບແຈ້ງເຕືອນ',
            notifLikes: 'ການກົດຖືກໃຈ',
            notifLikesDesc: 'ແຈ້ງເຕືອນເມື່ອມີຄົນກົດຖືກໃຈ',
            notifComments: 'ຄວາມຄິດເຫັນ',
            notifCommentsDesc: 'ແຈ້ງເຕືອນເມື່ອມີຄົນຄອມເມັ້ນ',
            notifMessages: 'ຂໍ້ຄວາມ',
            notifMessagesDesc: 'ແຈ້ງເຕືອນເມື່ອໄດ້ຮັບຂໍ້ຄວາມ',
            notifMatches: 'ການແມັດຊ໌',
            notifMatchesDesc: 'ແຈ້ງເຕືອນເມື່ອມີການແມັດຊ໌ໃໝ່',
            chatBubbleStyle: 'ສະໄຕລ໌ຟອງແຊັດ',
            chatBubbleStyleDesc: 'ປ່ຽນຮູບແບບຟອງຂໍ້ຄວາມ',
            autoDeleteMessages: 'ລົບຂໍ້ຄວາມອັດຕະໂນມັດ',
            autoDeleteMessagesDesc: 'ຕັ້ງເວລາລົບຂໍ້ຄວາມ',
            chatWallpaper: 'ພາບພື້ນຫຼັງແຊັດ',
            chatWallpaperDesc: 'ປັບແຕ່ງພື້ນຫຼັງແຊັດ',
            mediaAutoDownload: 'ດາວໂຫຼດມີເດຍອັດຕະໂນມັດ',
            mediaAutoDownloadDesc: 'ຮູບ, ວິດີໂອ, ໄຟລ໌',
            clearCache: 'ລ້າງແຄຊ',
            clearCacheDesc: 'ລົບຂໍ້ມູນທີ່ແຄຊໄວ້',
            dataUsage: 'ການໃຊ້ຂໍ້ມູນ',
            dataUsageDesc: 'ເບິ່ງປະລິມານຂໍ້ມູນທີ່ໃຊ້',
            downloadData: 'ດາວໂຫຼດຂໍ້ມູນຂອງຂ້ອຍ',
            downloadDataDesc: 'ສົ່ງອອກຂໍ້ມູນທັງໝົດຂອງທ່ານ',
            helpCenter: 'ສູນຊ່ວຍເຫຼືອ',
            helpCenterDesc: 'ຄຳຖາມທີ່ພົບເລື້ອຍ ແລະ ແນວທາງ',
            reportProblem: 'ລາຍງານບັນຫາ',
            reportProblemDesc: 'ແຈ້ງຂໍ້ຜິດພາດ ຫຼື ບັນຫາ',
            termsOfService: 'ເງື່ອນໄຂການໃຊ້ງານ',
            termsOfServiceDesc: 'ອ່ານຂໍ້ກຳນົດຂອງພວກເຮົາ',
            privacyPolicy: 'ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ',
            privacyPolicyDesc: 'ວິທີທີ່ພວກເຮົາຈັດການຂໍ້ມູນຂອງທ່ານ',
            about: 'ກ່ຽວກັບ',
            aboutDesc: 'ເວີຊັນແອັບ ແລະ ຂໍ້ມູນ',
            logout: 'ອອກຈາກລະບົບ',
            logoutDesc: 'ອອກຈາກລະບົບບັນຊີນີ້',
            deleteAccount: 'ລົົບບັນຊີ',
            deleteAccountDesc: 'ລົົບບັນຊີ ແລະ ຂໍ້ມູນທັງໝົດຢ່າງຖາວອນ',
            public: 'ສາທາລະນະ',
            friendsOnly: 'ສະເພາະໝູ່',
            private: 'ສ່ວນຕົວ',
            dark: 'ມືດ',
            light: 'ສະຫວ່າງ',
            system: 'ຕາມລະບົບ',
            small: 'ນ້ອຍ',
            medium: 'ກາງ',
            large: 'ໃຫຍ່',
            never: 'ບໍ່ເຄີຍ',
            after24h: 'ຫຼັງ 24 ຊົມ.',
            after7d: 'ຫຼັງ 7 ວັນ',
            after30d: 'ຫຼັງ 30 ວັນ',
            round: 'ມົນ',
            sharp: 'ຫຼ່ຽມ',
            minimal: 'ມິນິມອນ',
            version: 'ເວີຊັນ',
            cacheCleared: 'ລ້າງແຄຊຮຽບຮ້ອຍແລ້ວ',
            noBlockedUsers: 'ບໍ່ມີຜູ້ໃຊ້ທີ່ຖືກບລັອກ',
            unblock: 'ເລີກບລັອກ',
        },
        soul: {
            swipe: 'ປັດ',
            discoverNewFriends: 'ຄົ້ນຫາໝູ່ໃໝ່ທີ່ກົງໃຈທ່ານ',
            setupTitle: 'ຕັ້ງຄ່າ Soul Profile',
            setupSubtitle: 'ໂປຣໄຟລ໌ Soul ຈະແຍກຈາກໂປຣໄຟລ໌ຫຼັກຂອງທ່ານ ເພື່ອຄວາມເປັນສ່ວນຕົວໃນການຫາໝູ່ໃໝ່',
            importProfile: 'ດຶງຈາກໂປຣໄຟລ໌ຫຼັກ',
            importDesc: 'ຄັດລອກຊື່, ຮູບ, bio ຈາກໂປຣໄຟລ໌ຫຼັກມາເລີ່ມຕົ້ນ ແກ້ໄຂໄດ້ທີຫຼັງ',
            createNew: 'ສ້າງໂປຣໄຟລ໌ໃໝ່',
            createNewDesc: 'ກອກຂໍ້ມູນໃໝ່ທັງໝົດ ສ້າງຕົວຕົນອີກແບບໄດ້ເລີຍ!',
            profileReady: '✨ Soul Profile ຂອງທ່ານພ້ອມແລ້ວ! ເລີ່ມຫາໝູ່ໃໝ່ກັນເລີຍ!',
            resetProfile: 'ຕັ້ງຄ່າ Soul Profile ໃໝ່',
            discover: 'ຄົ້ນພົບ',
            connecting: 'ກຳລັງເຊື່ອມຕໍ່ກັບວິນຍານ...',
            noMoreSouls: 'ບໍ່ມີໝູ່ໃໝ່ໃນບໍລິເວນນີ້',
            seenEveryone: 'ທ່ານເບິ່ງໂປຣໄຟລ໌ທັງໝົດໃນເວລານີ້ແລ້ວ',
            findMore: 'ຫາໝູ່ໃໝ່ເພີ່ມ',
            matchWith: 'ແມັດຊ໌ກັບ {{name}} ແລ້ວ! ❤️',
            rewinded: 'ຢ້ອນກັບແລ້ວ ⏪',
            noRewind: 'ບໍ່ມີໂປຣໄຟລ໌ກ່ອນໜ້ານີ້ໃຫ້ຢ້ອນກັບ',
            superLiked: 'ທ່ານ Super Like {{name}}! ⚡',
            openingProfile: 'ກຳລັງເປີດໂປຣໄຟລ໌...',
            identityRevealed: 'ເປີດເຜີຍຕົວຕົນແລ້ວ! ✨ ຕອນນີ້ເຫັນໂປຣໄຟລ໌ຈິງໄດ້ແລ້ວ!',
            identityRequested: 'ສົ່ງຄຳຂໍເປີດເຜີຍແລ້ວ ❤️ ລໍຖ້າອີກຝ່າຍກົດຍອມຮັບ',
            identityError: 'ເປີດເຜີຍຕົວຕົນບໍ່ສຳເລັດ',
            updated: '✨ ອັບເດດ Soul Profile ຮຽບຮ້ອຍແລ້ວ!',
            mainProfileHint: 'ໂປຣໄຟລ໌ຫຼັກ: {{name}}',
            basicInfo: '📝 ຂໍ້ມູນພື້ນຖານ',
            tapToChange: 'ແຕະເພື່ອປ່ຽນຮູບ Soul',
            displayName: 'ຊື່ທີ່ສະແດງ',
            displayNamePlaceholder: 'ຊື່ທີ່ຕ້ອງການສະແດງໃນ Soul',
            bioPlaceholder: 'ຂຽນແນະນຳຕົວສັ້ນໆ...',
            age: 'ອາຍຸ',
            gender: 'ເພດ',
            male: 'ຊາຍ',
            female: 'ຍິງ',
            other: 'ອື່ນໆ',
            location: 'ທີ່ຢູ່ (ແຂວງ)',
            selectProvince: '-- ເລືອກແຂວງ --',
            interestsTitle: '🎯 ສິ່ງທີ່ສົນໃຈ',
            interestsHint: 'ເລືອກສິ່ງທີ່ທ່ານມັກ (1-6 ຢ່າງ) · ເລືອກແລ້ວ {{count}}/6',
            lookingForTitle: '💭 ກຳລັງມອງຫາຫຍັງ?',
            lookingForHint: 'ເລືອກໄດ້ຫຼາຍກວ່າ 1 ຢ່າງ',
            photosTitle: '📸 ຮູບພາບຂອງທ່ານ',
            photosHint: 'ກະລຸນາອັບໂຫຼດຮູບພາບຢ່າງໜ້ອຍ 2 ຮູບເພື່ອໃຫ້ໂປຣໄຟລ໌ເບິ່ງໜ້າສົນໃຈ',
            previewTitle: '✨ ຕົວຢ່າງໂປຣໄຟລ໌ Soul',
            lookingForLabel: 'ກຳລັງມອງຫາ:',
            startSoul: 'ເລີ່ມຕົ້ນໃຊ້ງານ Soul!',
            viewLikedSouls: 'ເບິ່ງຄົນທີ່ທ່ານຖືກໃຈ',
            editProfile: 'ແກ້ໄຂ Soul Profile',
            destinyPulse: '⚡ Destiny Pulse!',
            destinyNearby: 'ມີບາງຄົນກຳລັງປັດຫາຄູ່ໃນໄລຍະໃກ້ກັບທ່ານຕອນນີ້!',
            destinyIntense: 'ພະລັງງານຄວາມເຂົ້າກັນໄດ້ສູງຫຼາຍ! 🔥',
            viewPreview: 'ເບິ່ງຕົວຢ່າງໂປຣໄຟລ໌',
            interests: {
                music: 'ດົນຕີ',
                movies: 'ຮູບເງົາ',
                travel: 'ທ່ອງທ່ຽວ',
                food: 'ອາຫານ',
                sports: 'ກິລາ',
                gaming: 'ເກມ',
                art: 'ສິລະປະ',
                reading: 'ອ່ານປຶ້ມ',
                photography: 'ຖ່າຍຮູບ',
                cooking: 'ແຕ່ງກິນ',
                fitness: 'ອອກກຳລັງກາຍ',
                anime: 'ອານິເມະ',
                nature: 'ທຳມະຊາດ',
                tech: 'ເຕັກໂນໂລຊີ',
                fashion: 'ແຟຊັ່ນ',
                coffee: 'ກາເຟ',
                pet: 'ສັດລ້ຽງ',
                kpop: 'K-Pop',
            },
            looking: {
                friends: 'ໝູ່ລົມ',
                dating: 'ຫາຄູ່ເດດ',
                relationship: 'ຄວາມສຳພັນຈິງຈັງ',
                hangout: 'ອອກໄປທ່ຽວນຳກັນ',
                anything: 'ຫຍັງກໍໄດ້',
            },
        },
        chat: {
            search: 'ຄົ້ນຫາແຊັດ...',
            noChats: 'ຍັງບໍ່ມີແຊັດ',
            typeMessage: 'ພິມຂໍ້ຄວາມ...',
            online: 'ອອນໄລນ໌',
            lastSeen: 'ເຫັນຫຼ້າສຸດ',
            blockedUser: 'ບລັອກ {{name}} ຮຽບຮ້ອຍແລ້ວ',
            reportedUser: 'ລາຍງານ {{name}} ຮຽບຮ້ອຍແລ້ວ',
        },
        common: {
            loading: 'ກຳລັງໂຫຼດ...',
            error: 'ຂໍ້ຜິດພາດ',
            success: 'ສຳເລັດ',
            confirm: 'ຢືນຢັນ',
            cancel: 'ຍົກເລີກ',
            close: 'ປິດ',
            back: 'ກັບ',
            next: 'ຖັດໄປ',
            done: 'ສຳເລັດ',
            on: 'ເປີດ',
            off: 'ປິດ',
        },
    },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('flare_language') || 'th';
    });

    useEffect(() => {
        localStorage.setItem('flare_language', language);
        document.documentElement.setAttribute('lang', language);
    }, [language]);

    const t = (path, variables = {}) => {
        const keys = path.split('.');
        let result = translations[language];
        for (const key of keys) {
            result = result?.[key];
        }
        if (!result) return path;

        // Replace placeholders like {{name}}
        Object.keys(variables).forEach(key => {
            result = result.replace(new RegExp(`{{${key}}}`, 'g'), variables[key]);
        });

        return result;
    };

    const switchLanguage = (lang) => {
        if (translations[lang]) {
            setLanguage(lang);
        }
    };

    const availableLanguages = [
        { code: 'th', name: 'ไทย', flag: '🇹🇭' },
        { code: 'la', name: 'ລາວ', flag: '🇱🇦' },
        { code: 'en', name: 'English', flag: '🇺🇸' },
    ];

    return (
        <LanguageContext.Provider value={{ language, t, switchLanguage, availableLanguages }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};

export default LanguageContext;
